### PR TITLE
add explicit timestamps

### PR DESCRIPTION
**Pull request by mpadge**
Todd,
Your code only works if `locale` is compatible with the bike data (that is, US `locale` only). These changes ensure it works regardless of `locale`. They also `glob` out the other `data` files to avoid a bunch of garbage error messages.

And in case you're wondering, I'm adapting your code for some benchmarking tests against [this current fairly messy code](https://github.com/mpadge/bike-correlations). Short-term aim is to incorporate ability to load hire bike data into [this R package](https://github.com/ropensci/stplanr) - let me know if you're interested in contributing, otherwise at the very least i'll certainly keep you informed of the extent to which some of your code might end up being incorporated in `stplanr`.

### CODE REVIEW

**Comment by mpadge** [comment]
No sorry, that ain't quite right.. i'll get back to you

**Comment by mpadge** [comment]
Feel free to reject the PR, by the way, if you'd rather not incorporate these changes. I won't mind at all.

**Comment by toddwschneider** [comment]
Hi @mpadge thanks for the PR. I'm open to these changes, I just need to take a look and actually run them on my machine, then I'll get back to you with any questions!

**Comment by toddwschneider** [comment]
Hi @mpadge, I made a few updates to the repo, including setting the `datestyle` explicitly in this commit: https://github.com/toddwschneider/nyc-citibike-data/pull/5/commits/7b16ad013d9369e826173f27047ea2ed6930c198

Does that solve your issue? Seems simpler to me than altering the column types repeatedly

**Comment by mpadge** [comment]
I simply don't know Todd - That is of course the most sensible way to do it, but on my current install, `SET datestyle` only appears to work for `user=postgres`, and is **not** simply applied directly to a nominated database. That's what led to my admittedly much more convoluted way to doing things. I intend to try a clean container install to get to the bottom of the issue, for which I first have to fix my currently broken `lxd` ...

**Comment by mpadge** [comment]
Oh yeah, I meant to close that myself. Sorry i didn't get around to it. FYI: I've written an R package called [`bikedata`](https://github.com/mpadge/bikedata) that loads data from a heap of different cities. Makes these kinds of analyses much simpler now.

**Comment by toddwschneider** [comment]
Cool, I'll check it out!

**Pull request closed without merging**
